export const GAME_SETTINGS = {
  INITIAL_LIVES: 20,
  BONUS_LIVES_PER_LEVEL: 7,
  BASE_SCORE_PER_LEVEL: 100,
  SCORE_PER_REMAINING_LIFE: 10,
  SECRET_NUMBER_LENGTH: 4,
  JOKER_COST_LIVES: 2, 
};

export const LEADERBOARD_KEY = 'bullsAndCowsLeaderboard';