export const GAME_SETTINGS = {
  INITIAL_LIVES: 20,
  BONUS_LIVES_PER_LEVEL: 10, 
  BASE_SCORE_PER_LEVEL: 100,
  SCORE_PER_REMAINING_LIFE: 10,
  SECRET_NUMBER_LENGTH: 4,
  
  // НОВИ ЖОКЕРИ
  JOKER_REVEAL_COST: 2, 
  JOKER_POSITION_COST: 4,
};

export const LEADERBOARD_KEY = 'bullsAndCowsLeaderboard';